# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# model_script.py
# Created on: 2018-11-21 20:36:21.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
drumuri = "drumuri"
drumuri__2_ = drumuri
judete__2_ = drumuri__2_
drumuri__4_ = drumuri__2_
linie_Layer = "linie_Layer"
linieTab = "T:\\IE\\bd_ro.mdb\\linieTab"
judete = "judete"
judete__4_ = judete__2_
judete_layer = "judete_layer"
judTab = "T:\\IE\\bd_ro.mdb\\judTab"

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(drumuri, "NEW_SELECTION", "[NUME2] = 'E60'")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(drumuri__2_, linie_Layer, "", "", "OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE;TIP1 TIP1 VISIBLE NONE;NUME1 NUME1 VISIBLE NONE;TIP2 TIP2 VISIBLE NONE;NUME2 NUME2 VISIBLE NONE;TIP3 TIP3 VISIBLE NONE;NUME3 NUME3 VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE")

# Process: Copy Features
arcpy.CopyFeatures_management(linie_Layer, linieTab, "", "0", "0", "0")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(judete, "INTERSECT", drumuri__2_, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Make Feature Layer (2)
arcpy.MakeFeatureLayer_management(judete__2_, judete_layer, "", "", "OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE;nume nume VISIBLE NONE;resedinta resedinta VISIBLE NONE;orase orase VISIBLE NONE;municipii municipii VISIBLE NONE;comune comune VISIBLE NONE;S_ha S_ha VISIBLE NONE;sj sj VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE")

# Process: Copy Features (2)
arcpy.CopyFeatures_management(judete_layer, judTab, "", "0", "0", "0")

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(judete__2_, "CLEAR_SELECTION", "")

# Process: Select Layer By Attribute (3)
arcpy.SelectLayerByAttribute_management(drumuri__2_, "CLEAR_SELECTION", "")

